CPSTK: CommandObjectBase Class Reference
CommandObjectBase Class Reference
#include <itkCommandObjectBase.h>
Public Types
typedef CommandObjectBase Self
typedef ProcessObject Superclass
typedef SmartPointer< Self > Pointer
typedef SmartPointer< const Self > ConstPointer
Public Member Functions
virtual const char * GetNameOfClass () const
virtual const char * GetCommandName (void)=0
virtual const char * GetShortDescription (void) const
virtual const char * GetLongDescription (void) const
virtual int Execute (int nargs, const char *args[])=0
Protected Member Functions
CommandObjectBase ()
~CommandObjectBase ()
Protected Attributes
std::string m_ShortDescription
std::string m_LongDescription
Detailed Description
Definition at line 27 of file itkCommandObjectBase.h.
Member Typedef Documentation
typedef SmartPointer<const Self> ConstPointer
Definition at line 33 of file itkCommandObjectBase.h.
typedef SmartPointer<Self> Pointer
Definition at line 32 of file itkCommandObjectBase.h.
typedef CommandObjectBase Self
Definition at line 30 of file itkCommandObjectBase.h.
typedef ProcessObject Superclass
Definition at line 31 of file itkCommandObjectBase.h.
Constructor & Destructor Documentation
CommandObjectBase () [protected]
Definition at line 22 of file itkCommandObjectBase.cxx.
~CommandObjectBase () [protected]
Definition at line 26 of file itkCommandObjectBase.cxx.
Member Function Documentation
virtual int Execute (int nargs, const char * args[]) [pure virtual]
virtual const char* GetCommandName (void) [pure virtual]
Referenced by CommandObjectFactory::PrintHelp().
const char * GetLongDescription (void) const [virtual]
Definition at line 35 of file itkCommandObjectBase.cxx.
References CommandObjectBase::m_LongDescription.
virtual const char* GetNameOfClass () const [virtual]
Referenced by CommandObjectFactory::CreateCommandObject().
const char * GetShortDescription (void) const [virtual]
Definition at line 30 of file itkCommandObjectBase.cxx.
References CommandObjectBase::m_ShortDescription.
Referenced by CommandObjectFactory::PrintHelp().
Member Data Documentation
std::string m_LongDescription [protected]
Definition at line 48 of file itkCommandObjectBase.h.
Referenced by CommandObjectBase::GetLongDescription().
std::string m_ShortDescription [protected]
Definition at line 47 of file itkCommandObjectBase.h.
Referenced by CommandObjectBase::GetShortDescription().
The documentation for this class was generated from the following files:
itkCommandObjectBase.h
itkCommandObjectBase.cxx