CPSTK: ProlateSpheroidalTransform< TPixelType > Class Template Reference
ProlateSpheroidalTransform< TPixelType > Class Template Reference
Transformation class from Cartesian coordinates to Prolate Spheroidal Coordinates.
#include <itkProlateSpheroidalTransform.h>
Public Types
typedef ProlateSpheroidalTransform Self
typedef Transform< double, 3, 3 > Superclass
typedef SmartPointer< Self > Pointer
typedef SmartPointer< const Self > ConstPointer
typedef TPixelType ScalarType
typedef Superclass::ParametersType ParametersType
typedef Superclass::JacobianType JacobianType
typedef Superclass::InputVectorType InputVectorType
typedef
Superclass::OutputVectorType OutputVectorType
typedef
Superclass::InputCovariantVectorType InputCovariantVectorType
typedef
Superclass::OutputCovariantVectorType OutputCovariantVectorType
typedef
Superclass::InputVnlVectorType InputVnlVectorType
typedef
Superclass::OutputVnlVectorType OutputVnlVectorType
typedef Superclass::InputPointType InputPointType
typedef Superclass::OutputPointType OutputPointType
typedef
Superclass::InverseTransformBaseType InverseTransformBaseType
typedef
InverseTransformBaseType::Pointer InverseTransformBasePointer
typedef Matrix< ScalarType, 4, 4 > UniformMatrixType
typedef Matrix< ScalarType, 3, 3 > MatrixType
typedef Vector< ScalarType, 4 > UniformVectorType
typedef Point< ScalarType, 3 > PointType
typedef Vector< ScalarType, 3 > VectorType
typedef itk::CrossHelper
< VectorType > CrossHelperType
Public Member Functions
itkStaticConstMacro (InputSpaceDimension, unsigned int, 3)
itkStaticConstMacro (OutputSpaceDimension, unsigned int, 3)
itkStaticConstMacro (ParametersDimension, unsigned int, 9)
virtual const char * GetNameOfClass () const
virtual void SetForward (unsigned int _arg)
virtual unsigned int GetForward () const
virtual void ForwardOn ()
virtual void ForwardOff ()
void SetCenter (PointType point)
void SetLongAxisPoint (PointType point)
void SetShortAxisPoint (PointType point)
void DefineEllipsoid (PointType center, PointType longaxispoint, PointType shortaxispoint)
OutputPointType TransformPoint (const InputPointType &) const
OutputVectorType TransformVector (const InputVectorType &, const InputPointType &) const
OutputVnlVectorType TransformVector (const InputVnlVectorType &, const InputPointType &) const
OutputCovariantVectorType TransformCovariantVector (const InputCovariantVectorType &, const InputPointType &) const
void SetParameters (const ParametersType &)
void SetParametersByValue (const ParametersType &p)
const ParametersType & GetParameters (void) const
void SetFixedParameters (const ParametersType &t)
const ParametersType & GetFixedParameters (void) const
JacobianType & GetJacobian (const InputPointType &) const
vnl_matrix_fixed< TPixelType, 3, 3 > GetJacobianWithRespectToCoordinates (const InputPointType &) const
ScalarType GetJacobianDeterminantWithRespectToCoordinates (const InputPointType &) const
bool GetInverse (Self *inverse) const
void SetIdentity (void)
bool IsLinear () const
void EvaluateLocalBasis (InputPointType x, VectorType &n, VectorType &a, VectorType &d) const
PointType ToCartesian (PointType xsi) const
PointType ToProlate (PointType x) const
VectorType ToCartesian (VectorType v, PointType p) const
VectorType ToProlate (VectorType v, PointType p) const
virtual double GetLambda1 ()
virtual double GetLambda2 ()
virtual double GetLambda3 ()
virtual double GetEccentricity ()
virtual double GetSemiFociDistance ()
virtual PointType GetFocus1 ()
virtual PointType GetFocus2 ()
virtual PointType GetCenter ()
virtual VectorType GetAxis1 ()
virtual VectorType GetAxis2 ()
virtual VectorType GetAxis3 ()
void EvaluateScaleFactors (double xsi[3], double h[3]) const
double EvaluateFunction (PointType x) const
double EvaluateFunction (double x[3]) const
void EvaluateGradient (PointType x, VectorType &n) const
void EvaluateGradient (double x[3], double n[3]) const
double EstimateGeodesicLength1 (PointType xi, VectorType dxi, unsigned int divisions) const
double EstimateGeodesicLength2 (PointType xi, VectorType dxi, unsigned int divisions) const
Static Public Member Functions
static Pointer New ()
Protected Member Functions
ProlateSpheroidalTransform ()
~ProlateSpheroidalTransform ()
void PrintSelf (std::ostream &os, Indent indent) const
void ComputeTransformation (void)
Protected Attributes
PointType m_Center
PointType m_LongAxisPoint
PointType m_ShortAxisPoint
VectorType m_Axis1
VectorType m_Axis2
VectorType m_Axis3
double m_Coefficients [3]
double m_Lambda1
double m_Lambda2
double m_Lambda3
PointType m_Focus1
PointType m_Focus2
double m_Eccentricity
double m_SemiFociDistance
UniformMatrixType m_InternalTransform
UniformMatrixType m_InternalTransformInverse
CrossHelperType m_Cross
unsigned int m_Forward
Detailed Description
template<class TPixelType = double>
class itk::ProlateSpheroidalTransform< TPixelType >
Transformation class from Cartesian coordinates to Prolate Spheroidal Coordinates.
ProlateSpheroidalTransform is a transformation. Input parameters are 3 points defining a prolate spheroid: the center of the spheroid, the long axis point, and the short axis point.
Use DefineEllipsoid() with the three points as arguments to define the spheroid (ellipsoid).
You can also use separately the methods SetCenter() SetLongAxisPoint() and SetShortAxisPoint().
The ellipsoid is defined as :
whith . which means the ellipsoid is prolate and its long axis is the x-axis.
There is an "internal" transformation InternalTransformInverse that transform a point (or vector) in space to the x-axis centered ellipsoid. We use usual definition of the prolate spheroidal coordinates :
This class derives from an itk::Transform. Therefore beneficiates from all common methods for a transform, such as TransformPoint() or GetJacobian(). However, as this change of coordinates is not spacially homogeneous, you cannot use TransformVector() without indicating from which point this vector is defined.
The coordinate change can be "Forward" - from Cartesian towards Prolate Spheroidal Coordinates - or "Backward" - from Prolate Spheroidal towards Cartesian coordinates. Control the direction of the transform with SetForward() methods. By definition, the inverse of a Forward transformation is the related Backward transformation. Therefore, Accessing GetInverse() has the same effect as using the same transform but changing direction to "Backward".
It can also be seen as an implicit function (EvaluateFunction()) using the formula:
and its gradient (corresponding to first contravariant vector) using EvaluateGradient():
See also:
ProlateSpheroidTransformTensorFilter
Transform
Author:
Nicolas Toussaint, King's College London, nicolas.toussaint@kcl.ac.uk
Definition at line 108 of file itkProlateSpheroidalTransform.h.
Member Typedef Documentation
typedef SmartPointer<const Self> ConstPointer
Definition at line 114 of file itkProlateSpheroidalTransform.h.
typedef itk::CrossHelper<VectorType> CrossHelperType
typedefs definitions
Definition at line 162 of file itkProlateSpheroidalTransform.h.
typedef Superclass::InputCovariantVectorType InputCovariantVectorType
Standard covariant vector type for this class
Definition at line 135 of file itkProlateSpheroidalTransform.h.
typedef Superclass::InputPointType InputPointType
Standard coordinate point type for this class
Definition at line 143 of file itkProlateSpheroidalTransform.h.
typedef Superclass::InputVectorType InputVectorType
Standard vector type for this class.
Definition at line 131 of file itkProlateSpheroidalTransform.h.
typedef Superclass::InputVnlVectorType InputVnlVectorType
Standard vnl_vector type for this class.
Definition at line 139 of file itkProlateSpheroidalTransform.h.
typedef InverseTransformBaseType::Pointer InverseTransformBasePointer
Definition at line 149 of file itkProlateSpheroidalTransform.h.
typedef Superclass::InverseTransformBaseType InverseTransformBaseType
Base inverse transform type. This type should not be changed to the concrete inverse transform type or inheritance would be lost.
Definition at line 148 of file itkProlateSpheroidalTransform.h.
typedef Superclass::JacobianType JacobianType
Type of the Jacobian matrix.
Definition at line 128 of file itkProlateSpheroidalTransform.h.
typedef Matrix<ScalarType, 3, 3> MatrixType
typedefs definitions
Definition at line 154 of file itkProlateSpheroidalTransform.h.
typedef Superclass::OutputCovariantVectorType OutputCovariantVectorType
Definition at line 136 of file itkProlateSpheroidalTransform.h.
typedef Superclass::OutputPointType OutputPointType
Definition at line 144 of file itkProlateSpheroidalTransform.h.
typedef Superclass::OutputVectorType OutputVectorType
Definition at line 132 of file itkProlateSpheroidalTransform.h.
typedef Superclass::OutputVnlVectorType OutputVnlVectorType
Definition at line 140 of file itkProlateSpheroidalTransform.h.
typedef Superclass::ParametersType ParametersType
Type of the input parameters.
Definition at line 125 of file itkProlateSpheroidalTransform.h.
typedef SmartPointer<Self> Pointer
Definition at line 113 of file itkProlateSpheroidalTransform.h.
typedef Point<ScalarType, 3> PointType
typedefs definitions
Definition at line 158 of file itkProlateSpheroidalTransform.h.
typedef TPixelType ScalarType
Type of the scalar representing coordinate and vector elements.
Definition at line 117 of file itkProlateSpheroidalTransform.h.
typedef ProlateSpheroidalTransform Self
Definition at line 111 of file itkProlateSpheroidalTransform.h.
typedef Transform<double, 3, 3> Superclass
Definition at line 112 of file itkProlateSpheroidalTransform.h.
typedef Matrix<ScalarType, 4, 4> UniformMatrixType
typedefs definitions
Definition at line 152 of file itkProlateSpheroidalTransform.h.
typedef Vector<ScalarType, 4> UniformVectorType
typedefs definitions
Definition at line 156 of file itkProlateSpheroidalTransform.h.
typedef Vector<ScalarType, 3> VectorType
typedefs definitions
Definition at line 160 of file itkProlateSpheroidalTransform.h.
Constructor & Destructor Documentation
ProlateSpheroidalTransform () [protected]
~ProlateSpheroidalTransform () [protected]
Member Function Documentation
void ComputeTransformation (void) [protected]
void DefineEllipsoid (PointType center, PointType longaxispoint, PointType shortaxispoint) [inline]
defining the prolate spheroid using three landmark points. The center of the spheroid, the long axis point and the short axis point. From there a ellipsoid is defined using the expression
The spheroid is centered at origin [0,0,0] and its long axis to the x-axis, with . The transformation from a point in space to the centered spheroid is simply a translation (using the center point) and a rotation (orthonormal matrix), stored in m_InternalTransformInverse.
Some parameters are derived from this definition, such as :
The eigenvectors of the spheroid, normalized : ; ; and .
The eigenvalues of the spheroid taken as norms of the eigenvectors (obviously before normalization).
The coefficients of the ellipsoid: , and .
The semi-foci distance , half of distance between the 2 foci, is also the linear eccentricity .
The eccentricity : .
Definition at line 223 of file itkProlateSpheroidalTransform.h.
double EstimateGeodesicLength1 (PointType xi, VectorType dxi, unsigned int divisions) const
double EstimateGeodesicLength2 (PointType xi, VectorType dxi, unsigned int divisions) const
double EvaluateFunction (PointType x) const
Evaluate ellipsoid equation. The implicit function that is evaluated here is : The argument is a Point in Cartesian coordinates
double EvaluateFunction (double x[3]) const
Evaluate ellipsoid equation. The implicit function that is evaluated here is : The argument is a Point in Cartesian coordinates
void EvaluateGradient (PointType x, VectorType & n) const
Evaluate ellipsoid implicit function gradient. It is estimated in the centered ellipsoid coordinate system (point is transformed using InternalTransformInverse), with the coefficients of the ellipsoid. The argument is a Point in Cartesian coordinates .
It also corresponds to the first contravariant vector.
void EvaluateGradient (double x[3], double n[3]) const
Evaluate ellipsoid implicit function gradient. It is estimated in the centered ellipsoid coordinate system (point is transformed using InternalTransformInverse), with the coefficients of the ellipsoid. The argument is a Point in Cartesian coordinates .
It also corresponds to the first contravariant vector.
void EvaluateLocalBasis (InputPointType x, VectorType & n, VectorType & a, VectorType & d) const
from an input point
x (in Cartesian if Forward / in Prolate if !forward),
Evaluate local basis at a defined prolate spheroidal coordinate :
n : normal vector (radial) --> .
a : right ascension vector --> .
d : declination vector (circumferential) --> .
(n, a, d) is a local orthonormal prolate spheroid basis at position . It is estimated using the contravariant vector formulae. For instance,
Warning:
The contravariant basis is subject to a lot of sinus, cosinus, and hyperbolic function calculation, resulting in a possible numerical error, and inducing the non-orthogonality of the basis.
void EvaluateScaleFactors (double xsi[3], double h[3]) const
evaluate scale factors at prolate position :
virtual void ForwardOff () [virtual]
virtual void ForwardOn () [virtual]
virtual VectorType GetAxis1 () [virtual]
Recover the first eigenvector.
virtual VectorType GetAxis2 () [virtual]
Recover the second eigenvector.
virtual VectorType GetAxis3 () [virtual]
Recover the third eigenvector.
virtual PointType GetCenter () [virtual]
Recover the spheroid center.
virtual double GetEccentricity () [virtual]
Recover the spheroid eccentricity.
const ParametersType& GetFixedParameters (void) const [inline]
Get the Fixed Parameters.
Definition at line 289 of file itkProlateSpheroidalTransform.h.
virtual PointType GetFocus1 () [virtual]
Recover the spheroid first focus.
virtual PointType GetFocus2 () [virtual]
Recover the spheroid second focus.
virtual unsigned int GetForward () const [virtual]
bool GetInverse (Self * inverse) const
Get the inverse of this transform
JacobianType& GetJacobian (const InputPointType &) const
Compute the Jacobian of the transformation
This method computes the Jacobian matrix of the transformation at a given input point. The rank of the Jacobian will also indicate if the transform is invertible at this point.
The Jacobian is be expressed as a matrix of partial derivatives of the output point components with respect to the parameters that defined the transform:
ScalarType GetJacobianDeterminantWithRespectToCoordinates (const InputPointType &) const
Get the jacobian determinant of transformation with respect to the coordinates at a specific point
vnl_matrix_fixed<TPixelType,3,3> GetJacobianWithRespectToCoordinates (const InputPointType &) const
Get the jacobian of the transformation with respect to the coordinates at a specific point
It can also be seen in our case as a local contravariant basis,
virtual double GetLambda1 () [virtual]
Recover the spheroid first eigenvalue.
virtual double GetLambda2 () [virtual]
Recover the spheroid second eigenvalue.
virtual double GetLambda3 () [virtual]
Recover the spheroid third eigenvalue.
virtual const char* GetNameOfClass () const [virtual]
const ParametersType& GetParameters (void) const [inline]
Get the Transformation Parameters. In our case the parameters correspond to the cartesian coordinates of succesively the center, the long axis and the long axis points of the ellipsoid.
Definition at line 276 of file itkProlateSpheroidalTransform.h.
virtual double GetSemiFociDistance () [virtual]
Recover the spheroid semi foci distance (a)
bool IsLinear () const [inline]
Indicates that this transform is linear. That is, given two points P and Q, and scalar coefficients a and b, then
T(a*P + b*Q) = a * T(P) + b * T(Q)
Definition at line 351 of file itkProlateSpheroidalTransform.h.
itkStaticConstMacro (InputSpaceDimension , unsigned int, 3)
Dimension of the domain space.
itkStaticConstMacro (ParametersDimension , unsigned int, 9)
itkStaticConstMacro (OutputSpaceDimension , unsigned int, 3)
static Pointer New () [static]
generic constructors
Referenced by TensorMeshCostFunction::GetValue(), TensorMeshImageHybridCostFunction3::RecoverOutput(), and TensorMeshImageHybridCostFunction3::UpdatePipeline().
void PrintSelf (std::ostream & os, Indent indent) const [protected]
void SetCenter (PointType point) [inline]
Set the center point of the ellipsoid separately. Of course it has to be in Cartesian coordinates - as the center point has [0,0,0] as Prolate Spheroidal coordinates by definition.
Definition at line 180 of file itkProlateSpheroidalTransform.h.
void SetFixedParameters (const ParametersType & t) [inline]
Set the fixed parameters and update internal transformation.
Definition at line 282 of file itkProlateSpheroidalTransform.h.
virtual void SetForward (unsigned int _arg) [virtual]
Set the direction of the transformation. If Forward is set to 1, then the transformation is from Cartesian towards Prolate Spheroidal coordinates, and vice-versa.
void SetIdentity (void)
Set the transform to identity. Basically remove (and unregister) the displacement field from the transform
void SetLongAxisPoint (PointType point) [inline]
Set the long axis point of the ellipsoid separately. Of course it has to be in Cartesian coordinates - as the center point has [0,0,0] as Prolate Spheroidal coordinates by definition.
Definition at line 189 of file itkProlateSpheroidalTransform.h.
void SetParameters (const ParametersType &)
Set the transformation parameters and update internal transformation. SetParameters gives the transform the option to set it's parameters by keeping a reference to the parameters, or by copying. To force the transform to copy it's parameters call SetParametersByValue.
In our case the parameters correspond to the cartesian coordinates of succesively the center, the long axis and the long axis points of the ellipsoid.
See also:
SetParametersByValue
void SetParametersByValue (const ParametersType & p)
Set the transformation parameters and update internal transformation. This method forces the transform to copy the parameters. The default implementation is to call SetParameters. This call must be overridden if the transform normally implements SetParameters by keeping a reference to the parameters.
In our case the parameters correspond to the cartesian coordinates of succesively the center, the long axis and the short axis points of the ellipsoid.
See also:
SetParameters
void SetShortAxisPoint (PointType point) [inline]
Set the short axis point of the ellipsoid separately. Of course it has to be in Cartesian coordinates.
Definition at line 198 of file itkProlateSpheroidalTransform.h.
VectorType ToCartesian (VectorType v, PointType p) const
PointType ToCartesian (PointType xsi) const
Transforms a point between prolate spheroidal coordinates towards Cartesian coordinates.
and then the transformation InternalTransform iis used to go from zero-centered ellipsoid to the true point in space.
PointType ToProlate (PointType x) const
Not as easy as it seems...
By using the trignometric identity and the hyperbolic identity , we find .
If we note ; ; ; and . Then the hyperbolic identity gives us a polynome in :
Since only one of the root is possible, we find (is positive). then from the trigonometric identity, we have , from which we find since also positive.
is simply derived from the projection of the cartesian point onto the plane , i.e. .
VectorType ToProlate (VectorType v, PointType p) const
OutputCovariantVectorType TransformCovariantVector (const InputCovariantVectorType & , const InputPointType &) const
Method to transform a CovariantVector.
OutputPointType TransformPoint (const InputPointType &) const
Method to transform a point.
OutputVectorType TransformVector (const InputVectorType & , const InputPointType &) const
Method to transform a vector.
OutputVnlVectorType TransformVector (const InputVnlVectorType & , const InputPointType &) const
Method to transform a vnl_vector.
Member Data Documentation
VectorType m_Axis1 [protected]
Definition at line 552 of file itkProlateSpheroidalTransform.h.
VectorType m_Axis2 [protected]
Definition at line 553 of file itkProlateSpheroidalTransform.h.
VectorType m_Axis3 [protected]
Definition at line 554 of file itkProlateSpheroidalTransform.h.
PointType m_Center [protected]
Definition at line 549 of file itkProlateSpheroidalTransform.h.
double m_Coefficients[3] [protected]
Definition at line 556 of file itkProlateSpheroidalTransform.h.
CrossHelperType m_Cross [protected]
Definition at line 569 of file itkProlateSpheroidalTransform.h.
double m_Eccentricity [protected]
Definition at line 563 of file itkProlateSpheroidalTransform.h.
PointType m_Focus1 [protected]
Definition at line 561 of file itkProlateSpheroidalTransform.h.
PointType m_Focus2 [protected]
Definition at line 562 of file itkProlateSpheroidalTransform.h.
unsigned int m_Forward [protected]
Definition at line 570 of file itkProlateSpheroidalTransform.h.
UniformMatrixType m_InternalTransform [protected]
Definition at line 566 of file itkProlateSpheroidalTransform.h.
UniformMatrixType m_InternalTransformInverse [protected]
Definition at line 567 of file itkProlateSpheroidalTransform.h.
double m_Lambda1 [protected]
Definition at line 557 of file itkProlateSpheroidalTransform.h.
double m_Lambda2 [protected]
Definition at line 558 of file itkProlateSpheroidalTransform.h.
double m_Lambda3 [protected]
Definition at line 559 of file itkProlateSpheroidalTransform.h.
PointType m_LongAxisPoint [protected]
Definition at line 550 of file itkProlateSpheroidalTransform.h.
double m_SemiFociDistance [protected]
Definition at line 564 of file itkProlateSpheroidalTransform.h.
PointType m_ShortAxisPoint [protected]
Definition at line 551 of file itkProlateSpheroidalTransform.h.
The documentation for this class was generated from the following file:
itkProlateSpheroidalTransform.h