CPSTK: CommandObjectFactory Class Reference
CommandObjectFactory Class Reference
#include <itkCommandObjectFactory.h>
Public Types
typedef CommandObjectFactory Self
typedef Object Superclass
typedef SmartPointer< Self > Pointer
typedef SmartPointer< const Self > ConstPointer
typedef
::itk::CommandObjectBase::Pointer CommandObjectBasePointer
Public Member Functions
virtual const char * GetNameOfClass () const
Static Public Member Functions
static CommandObjectBasePointer CreateCommandObject (const char *name)
static void PrintHelp (std::ostream &os, Indent indent)
Protected Member Functions
CommandObjectFactory ()
~CommandObjectFactory ()
Detailed Description
Definition at line 26 of file itkCommandObjectFactory.h.
Member Typedef Documentation
typedef ::itk::CommandObjectBase::Pointer CommandObjectBasePointer
Convenient typedefs.
Definition at line 38 of file itkCommandObjectFactory.h.
typedef SmartPointer<const Self> ConstPointer
Definition at line 33 of file itkCommandObjectFactory.h.
typedef SmartPointer<Self> Pointer
Definition at line 32 of file itkCommandObjectFactory.h.
typedef CommandObjectFactory Self
Standard class typedefs.
Definition at line 30 of file itkCommandObjectFactory.h.
typedef Object Superclass
Definition at line 31 of file itkCommandObjectFactory.h.
Constructor & Destructor Documentation
CommandObjectFactory () [protected]
~CommandObjectFactory () [protected]
Member Function Documentation
CommandObjectBase::Pointer CreateCommandObject (const char * name) [static]
Create the appropriate CommandObject.
Definition at line 29 of file itkCommandObjectFactory.cxx.
References CommandObjectBase::GetNameOfClass().
Referenced by main().
virtual const char* GetNameOfClass () const [virtual]
Class Methods used to interface with the registered factories Run-time type information (and related methods).
void PrintHelp (std::ostream & os, Indent indent) [static]
Print help messages of all registered commands
Definition at line 60 of file itkCommandObjectFactory.cxx.
References CommandObjectBase::GetCommandName(), and CommandObjectBase::GetShortDescription().
Referenced by main().
The documentation for this class was generated from the following files:
itkCommandObjectFactory.h
itkCommandObjectFactory.cxx