CPSTK: TensorMeshImageHybridCostFunction3 Class Reference
TensorMeshImageHybridCostFunction3 Class Reference
#include <itkTensorMeshImageHybridCostFunction3.h>
Public Types
enum KernelTypeIds { Gaussian = 0, BSpline, KaiserBessel }
enum AttachTermTypeIds { MeanSquareDistance = 0, MeanSquareAngle }
typedef
TensorMeshImageHybridCostFunction3 Self
typedef SingleValuedCostFunction Superclass
typedef SmartPointer< Self > Pointer
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::MeasureType MeasureType
typedef Superclass::DerivativeType DerivativeType
typedef Superclass::ParametersType ParametersType
typedef
Superclass::ParametersValueType ParametersValueType
typedef double ScalarType
typedef
ProlateSpheroidalTransform
< ScalarType > TransformType
typedef Tensor< ScalarType, 3 > TensorType
typedef Vector< ScalarType, 3 > VectorType
typedef Image< VectorType, 3 > DisplacementFieldType
typedef
TensorImageToMeshFilter
< TensorType, 3 > ImageToMeshType
typedef
TensorMeshToImageFilter
< TensorType, 3 > MeshToImageType
typedef ImageToMeshType::MeshType MeshType
typedef ImageToMeshType::ImageType ImageType
typedef
MeshToImageType::DomainImageType DomainImageType
typedef MeshType::PointType PointType
typedef MeshType::PointIdentifier PointIdentifier
typedef MeshType::PointsContainer PointContainer
typedef
MeshType::PointDataContainer PixelContainer
typedef WarpTensorMeshFilter
< MeshType,
DisplacementFieldType > WarperType
typedef
ProlateSpheroidalTransformTensorMeshFilter
< MeshType > TransformerType
typedef
GaussianInterpolationTensorMeshFilter2
< MeshType > Interpolator2Type
typedef GaussianKernelFunction GaussianKernelFunctionType
typedef BSplineKernelFunction< 3 > BSplineKernelFunctionType
typedef KaiserBesselKernelFunction KaiserBesselKernelType
Public Member Functions
virtual const char * GetNameOfClass () const
virtual unsigned int GetKernelType () const
virtual void SetKernelType (unsigned int _arg)
virtual unsigned int GetAttachTermType () const
virtual void SetAttachTermType (unsigned int _arg)
virtual unsigned int GetNumberOfParameters (void) const
virtual MeasureType GetValue (const ParametersType &parameters) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const
virtual void GetOutputTerms (const ParametersType &parameters, double terms[2]) const
void GetBounds (ParametersValueType bds[2][100])
void SetBounds (ParametersValueType bds[2][100])
virtual unsigned int GetUseProlateSpheroidalCoordinates ()
virtual void SetUseProlateSpheroidalCoordinates (unsigned int _arg)
virtual void UseProlateSpheroidalCoordinatesOn ()
virtual void UseProlateSpheroidalCoordinatesOff ()
void SetInputs (MeshType::Pointer data, ImageType::Pointer reference)
void SetDisplacementFields (DisplacementFieldType::Pointer forward, DisplacementFieldType::Pointer backward)
void SetTransform (TransformType::Pointer forward)
virtual double GetLambda () const
virtual void SetLambda (double _arg)
virtual MeasureType GetBeta ()
virtual void SetBeta (MeasureType _arg)
virtual Interpolator2Type * GetInterpolator ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
TensorMeshImageHybridCostFunction3 ()
virtual ~TensorMeshImageHybridCostFunction3 ()
MeshType::Pointer RecoverOutput (MeshType::Pointer mesh) const
virtual void GetValueInternal (const ParametersType &parameters, MeasureType terms[2]) const
virtual void UpdatePipeline (void)
virtual MeasureType EstimateMeanSquaredDistanceBetweenTensorFields (const MeshType::Pointer tensors1, const MeshType::Pointer tensors2) const
virtual MeasureType EstimateMeanSquaredAngleBetweenTensorFields (const MeshType::Pointer tensors1, const MeshType::Pointer tensors2) const
virtual MeasureType EstimateTensorFieldTotalVariation (MeshType::Pointer mesh) const
Detailed Description
Definition at line 37 of file itkTensorMeshImageHybridCostFunction3.h.
Member Typedef Documentation
typedef BSplineKernelFunction<3> BSplineKernelFunctionType
Definition at line 74 of file itkTensorMeshImageHybridCostFunction3.h.
typedef SmartPointer<const Self> ConstPointer
Definition at line 45 of file itkTensorMeshImageHybridCostFunction3.h.
typedef Superclass::DerivativeType DerivativeType
Definition at line 50 of file itkTensorMeshImageHybridCostFunction3.h.
typedef Image<VectorType, 3> DisplacementFieldType
Definition at line 58 of file itkTensorMeshImageHybridCostFunction3.h.
typedef MeshToImageType::DomainImageType DomainImageType
Definition at line 63 of file itkTensorMeshImageHybridCostFunction3.h.
typedef GaussianKernelFunction GaussianKernelFunctionType
Definition at line 73 of file itkTensorMeshImageHybridCostFunction3.h.
typedef TensorImageToMeshFilter<TensorType, 3> ImageToMeshType
Definition at line 59 of file itkTensorMeshImageHybridCostFunction3.h.
typedef ImageToMeshType::ImageType ImageType
Definition at line 62 of file itkTensorMeshImageHybridCostFunction3.h.
typedef GaussianInterpolationTensorMeshFilter2<MeshType> Interpolator2Type
Definition at line 71 of file itkTensorMeshImageHybridCostFunction3.h.
typedef KaiserBesselKernelFunction KaiserBesselKernelType
Definition at line 75 of file itkTensorMeshImageHybridCostFunction3.h.
typedef Superclass::MeasureType MeasureType
Definition at line 47 of file itkTensorMeshImageHybridCostFunction3.h.
typedef TensorMeshToImageFilter<TensorType, 3> MeshToImageType
Definition at line 60 of file itkTensorMeshImageHybridCostFunction3.h.
typedef ImageToMeshType::MeshType MeshType
Definition at line 61 of file itkTensorMeshImageHybridCostFunction3.h.
typedef Superclass::ParametersType ParametersType
Definition at line 51 of file itkTensorMeshImageHybridCostFunction3.h.
typedef Superclass::ParametersValueType ParametersValueType
Definition at line 52 of file itkTensorMeshImageHybridCostFunction3.h.
typedef MeshType::PointDataContainer PixelContainer
Definition at line 67 of file itkTensorMeshImageHybridCostFunction3.h.
typedef MeshType::PointsContainer PointContainer
Definition at line 66 of file itkTensorMeshImageHybridCostFunction3.h.
typedef SmartPointer<Self> Pointer
Definition at line 44 of file itkTensorMeshImageHybridCostFunction3.h.
typedef MeshType::PointIdentifier PointIdentifier
Definition at line 65 of file itkTensorMeshImageHybridCostFunction3.h.
typedef MeshType::PointType PointType
Definition at line 64 of file itkTensorMeshImageHybridCostFunction3.h.
typedef double ScalarType
Definition at line 54 of file itkTensorMeshImageHybridCostFunction3.h.
typedef TensorMeshImageHybridCostFunction3 Self
Standard class typedefs.
Definition at line 42 of file itkTensorMeshImageHybridCostFunction3.h.
typedef SingleValuedCostFunction Superclass
Definition at line 43 of file itkTensorMeshImageHybridCostFunction3.h.
typedef Tensor<ScalarType, 3> TensorType
Definition at line 56 of file itkTensorMeshImageHybridCostFunction3.h.
typedef ProlateSpheroidalTransformTensorMeshFilter<MeshType> TransformerType
Definition at line 70 of file itkTensorMeshImageHybridCostFunction3.h.
typedef ProlateSpheroidalTransform<ScalarType> TransformType
Definition at line 55 of file itkTensorMeshImageHybridCostFunction3.h.
typedef Vector<ScalarType, 3> VectorType
Definition at line 57 of file itkTensorMeshImageHybridCostFunction3.h.
typedef WarpTensorMeshFilter<MeshType, DisplacementFieldType> WarperType
Definition at line 69 of file itkTensorMeshImageHybridCostFunction3.h.
Member Enumeration Documentation
enum AttachTermTypeIds
Enumerator:
MeanSquareDistance
MeanSquareAngle
Definition at line 86 of file itkTensorMeshImageHybridCostFunction3.h.
enum KernelTypeIds
Enumerator:
Gaussian
BSpline
KaiserBessel
Definition at line 77 of file itkTensorMeshImageHybridCostFunction3.h.
Constructor & Destructor Documentation
TensorMeshImageHybridCostFunction3 () [protected]
Definition at line 29 of file itkTensorMeshImageHybridCostFunction3.cxx.
References TensorMeshImageHybridCostFunction3::Gaussian, ProlateSpheroidalTransformTensorMeshFilter< TMesh >::New(), and WarpTensorMeshFilter< TMesh, TDisplacementField >::New().
~TensorMeshImageHybridCostFunction3 () [protected, virtual]
Definition at line 63 of file itkTensorMeshImageHybridCostFunction3.cxx.
Member Function Documentation
TensorMeshImageHybridCostFunction3::MeasureType EstimateMeanSquaredAngleBetweenTensorFields (const MeshType::Pointer tensors1, const MeshType::Pointer tensors2) const [protected, virtual]
This method mean square angle (between main eigen vectors) of 2 distinct tensor fields Tensor arrays must have same size : check is performed.
Definition at line 243 of file itkTensorMeshImageHybridCostFunction3.cxx.
TensorMeshImageHybridCostFunction3::MeasureType EstimateMeanSquaredDistanceBetweenTensorFields (const MeshType::Pointer tensors1, const MeshType::Pointer tensors2) const [protected, virtual]
This method mean square distance (in the sense of Frobenius) of 2 distinct tensor fields Tensor arrays must have same size : check is performed.
Definition at line 197 of file itkTensorMeshImageHybridCostFunction3.cxx.
TensorMeshImageHybridCostFunction3::MeasureType EstimateTensorFieldTotalVariation (MeshType::Pointer mesh) const [protected, virtual]
Definition at line 139 of file itkTensorMeshImageHybridCostFunction3.cxx.
virtual unsigned int GetAttachTermType () const [virtual]
virtual MeasureType GetBeta () [virtual]
void GetBounds (ParametersValueType bds[2][100]) [inline]
Get/Set the bounds of the cost function in the parameter space. If a value is asked with parameters outside those bounds, a maximal cost function value will be returned.
Definition at line 109 of file itkTensorMeshImageHybridCostFunction3.h.
virtual void GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const [inline, virtual]
Definition at line 98 of file itkTensorMeshImageHybridCostFunction3.h.
virtual Interpolator2Type* GetInterpolator () [virtual]
virtual unsigned int GetKernelType () const [virtual]
virtual double GetLambda () const [virtual]
Get/Set the lambda smoothness ratio to use as a trade-off between the data attach term and the regularity total variation term.
virtual const char* GetNameOfClass () const [virtual]
virtual unsigned int GetNumberOfParameters (void) const [inline, virtual]
Definition at line 94 of file itkTensorMeshImageHybridCostFunction3.h.
void GetOutputTerms (const ParametersType & parameters, double terms[2]) const [virtual]
Definition at line 69 of file itkTensorMeshImageHybridCostFunction3.cxx.
virtual unsigned int GetUseProlateSpheroidalCoordinates () [virtual]
TensorMeshImageHybridCostFunction3::MeasureType GetValue (const ParametersType & parameters) const [virtual]
Definition at line 77 of file itkTensorMeshImageHybridCostFunction3.cxx.
void GetValueInternal (const ParametersType & parameters, MeasureType terms[2]) const [protected, virtual]
Definition at line 97 of file itkTensorMeshImageHybridCostFunction3.cxx.
static Pointer New () [static]
TensorMeshImageHybridCostFunction3::MeshType::Pointer RecoverOutput (MeshType::Pointer mesh) const [protected]
Definition at line 381 of file itkTensorMeshImageHybridCostFunction3.cxx.
References ProlateSpheroidalTransform< TPixelType >::New(), WarpTensorMeshFilter< TMesh, TDisplacementField >::New(), and ProlateSpheroidalTransformTensorMeshFilter< TMesh >::New().
virtual void SetAttachTermType (unsigned int _arg) [virtual]
virtual void SetBeta (MeasureType _arg) [virtual]
void SetBounds (ParametersValueType bds[2][100]) [inline]
Get/Set the bounds of the cost function in the parameter space. If a value is asked with parameters outside those bounds, a maximal cost function value will be returned.
Definition at line 118 of file itkTensorMeshImageHybridCostFunction3.h.
void SetDisplacementFields (DisplacementFieldType::Pointer forward, DisplacementFieldType::Pointer backward) [inline]
Definition at line 139 of file itkTensorMeshImageHybridCostFunction3.h.
void SetInputs (MeshType::Pointer data, ImageType::Pointer reference) [inline]
Set the variables of this cost function.
Parameters:
pts is an array of positions where the measured data are.
Definition at line 132 of file itkTensorMeshImageHybridCostFunction3.h.
virtual void SetKernelType (unsigned int _arg) [virtual]
virtual void SetLambda (double _arg) [virtual]
Get/Set the lambda smoothness ratio to use as a trade-off between the data attach term and the regularity total variation term.
void SetTransform (TransformType::Pointer forward) [inline]
Definition at line 146 of file itkTensorMeshImageHybridCostFunction3.h.
virtual void SetUseProlateSpheroidalCoordinates (unsigned int _arg) [virtual]
void UpdatePipeline (void) [protected, virtual]
Definition at line 297 of file itkTensorMeshImageHybridCostFunction3.cxx.
References TensorMeshImageHybridCostFunction3::BSpline, TensorMeshImageHybridCostFunction3::Gaussian, TensorMeshImageHybridCostFunction3::KaiserBessel, and ProlateSpheroidalTransform< TPixelType >::New().
virtual void UseProlateSpheroidalCoordinatesOff () [virtual]
virtual void UseProlateSpheroidalCoordinatesOn () [virtual]
The documentation for this class was generated from the following files:
itkTensorMeshImageHybridCostFunction3.h
itkTensorMeshImageHybridCostFunction3.cxx