CPSTK: GetPot Class Reference
GetPot Class Reference
#include <GetPot.h>
Classes
struct variable
Public Member Functions
GetPot ()
GetPot (const GetPot &)
GetPot (const int argc_, char **argv_, const char *FieldSeparator=0x0)
GetPot (const char *FileName, const char *CommentStart=0x0, const char *CommentEnd=0x0, const char *FieldSeparator=0x0)
~GetPot ()
GetPot & operator= (const GetPot &)
void absorb (const GetPot &That)
void clear_requests ()
void disable_request_recording ()
void enable_request_recording ()
const char * operator[] (unsigned Idx) const
int get (unsigned Idx, int Default) const
double get (unsigned Idx, const double &Default) const
const char * get (unsigned Idx, const char *Default) const
unsigned size () const
bool options_contain (const char *FlagList) const
bool argument_contains (unsigned Idx, const char *FlagList) const
int operator() (const char *VarName, int Default) const
double operator() (const char *VarName, const double &Default) const
const char * operator() (const char *VarName, const char *Default) const
int operator() (const char *VarName, int Default, unsigned Idx) const
double operator() (const char *VarName, const double &Default, unsigned Idx) const
const char * operator() (const char *VarName, const char *Default, unsigned Idx) const
void set (const char *VarName, const char *Value, const bool Requested=true)
void set (const char *VarName, const double &Value, const bool Requested=true)
void set (const char *VarName, const int Value, const bool Requested=true)
unsigned vector_variable_size (const char *VarName) const
STRING_VECTOR get_variable_names () const
STRING_VECTOR get_section_names () const
void set_prefix (const char *Prefix)
bool search_failed () const
void disable_loop ()
void enable_loop ()
void reset_cursor ()
void init_multiple_occurrence ()
bool search (const char *option)
bool search (unsigned No, const char *P,...)
int next (int Default)
double next (const double &Default)
const char * next (const char *Default)
int follow (int Default, const char *Option)
double follow (const double &Default, const char *Option)
const char * follow (const char *Default, const char *Option)
int follow (int Default, unsigned No, const char *Option,...)
double follow (const double &Default, unsigned No, const char *Option,...)
const char * follow (const char *Default, unsigned No, const char *Option,...)
int direct_follow (int Default, const char *Option)
double direct_follow (const double &Default, const char *Option)
const char * direct_follow (const char *Default, const char *Option)
void reset_nominus_cursor ()
STRING_VECTOR nominus_vector () const
unsigned nominus_size () const
const char * next_nominus ()
STRING_VECTOR unidentified_arguments (unsigned Number, const char *Known,...) const
STRING_VECTOR unidentified_arguments (const STRING_VECTOR &Knowns) const
STRING_VECTOR unidentified_arguments () const
STRING_VECTOR unidentified_options (unsigned Number, const char *Known,...) const
STRING_VECTOR unidentified_options (const STRING_VECTOR &Knowns) const
STRING_VECTOR unidentified_options () const
std::string unidentified_flags (const char *Known, int ArgumentNumber) const
STRING_VECTOR unidentified_variables (unsigned Number, const char *Known,...) const
STRING_VECTOR unidentified_variables (const STRING_VECTOR &Knowns) const
STRING_VECTOR unidentified_variables () const
STRING_VECTOR unidentified_sections (unsigned Number, const char *Known,...) const
STRING_VECTOR unidentified_sections (const STRING_VECTOR &Knowns) const
STRING_VECTOR unidentified_sections () const
STRING_VECTOR unidentified_nominuses (unsigned Number, const char *Known,...) const
STRING_VECTOR unidentified_nominuses (const STRING_VECTOR &Knowns) const
STRING_VECTOR unidentified_nominuses () const
int print () const
Detailed Description
Definition at line 57 of file GetPot.h.
Constructor & Destructor Documentation
GetPot () [inline]
Definition at line 368 of file GetPot.h.
GetPot (const GetPot & That) [inline]
Definition at line 426 of file GetPot.h.
References operator=().
GetPot (const int argc_, char ** argv_, const char * FieldSeparator = 0x0) [inline]
Definition at line 378 of file GetPot.h.
GetPot (const char * FileName, const char * CommentStart = 0x0, const char * CommentEnd = 0x0, const char * FieldSeparator = 0x0) [inline]
Definition at line 404 of file GetPot.h.
~GetPot () [inline]
Definition at line 430 of file GetPot.h.
References victorate.
Member Function Documentation
void absorb (const GetPot & That) [inline]
Definition at line 460 of file GetPot.h.
bool argument_contains (unsigned Idx, const char * FlagList) const [inline]
Definition at line 1160 of file GetPot.h.
void clear_requests () [inline]
Definition at line 472 of file GetPot.h.
int direct_follow (int Default, const char * Option) [inline]
Definition at line 1072 of file GetPot.h.
double direct_follow (const double & Default, const char * Option) [inline]
Definition at line 1085 of file GetPot.h.
const char * direct_follow (const char * Default, const char * Option) [inline]
Definition at line 1098 of file GetPot.h.
void disable_loop () [inline]
Definition at line 118 of file GetPot.h.
Referenced by init_multiple_occurrence().
void disable_request_recording () [inline]
Definition at line 77 of file GetPot.h.
void enable_loop () [inline]
Definition at line 119 of file GetPot.h.
void enable_request_recording () [inline]
Definition at line 78 of file GetPot.h.
int follow (int Default, const char * Option) [inline]
Definition at line 981 of file GetPot.h.
References next(), and search().
double follow (const double & Default, const char * Option) [inline]
Definition at line 989 of file GetPot.h.
References next(), and search().
const char * follow (const char * Default, const char * Option) [inline]
Definition at line 997 of file GetPot.h.
References next(), and search().
int follow (int Default, unsigned No, const char * Option, ...) [inline]
Definition at line 1007 of file GetPot.h.
References next(), and search().
const char * follow (const char * Default, unsigned No, const char * Option, ...) [inline]
Definition at line 1048 of file GetPot.h.
References next(), and search().
double follow (const double & Default, unsigned No, const char * Option, ...) [inline]
Definition at line 1028 of file GetPot.h.
References next(), and search().
double get (unsigned Idx, const double & Default) const [inline]
Definition at line 896 of file GetPot.h.
const char * get (unsigned Idx, const char * Default) const [inline]
Definition at line 903 of file GetPot.h.
int get (unsigned Idx, int Default) const [inline]
Definition at line 889 of file GetPot.h.
STRING_VECTOR get_section_names () const [inline]
Definition at line 1380 of file GetPot.h.
STRING_VECTOR get_variable_names () const [inline]
Definition at line 1368 of file GetPot.h.
void init_multiple_occurrence () [inline]
Definition at line 878 of file GetPot.h.
References disable_loop(), and reset_cursor().
int next (int Default) [inline]
Definition at line 916 of file GetPot.h.
Referenced by follow().
double next (const double & Default) [inline]
Definition at line 932 of file GetPot.h.
const char * next (const char * Default) [inline]
Definition at line 949 of file GetPot.h.
const char * next_nominus () [inline]
Definition at line 1218 of file GetPot.h.
unsigned nominus_size () const [inline]
Definition at line 148 of file GetPot.h.
STRING_VECTOR nominus_vector () const [inline]
Definition at line 1201 of file GetPot.h.
int operator() (const char * VarName, int Default, unsigned Idx) const [inline]
Definition at line 1266 of file GetPot.h.
double operator() (const char * VarName, const double & Default, unsigned Idx) const [inline]
Definition at line 1277 of file GetPot.h.
const char * operator() (const char * VarName, const char * Default, unsigned Idx) const [inline]
Definition at line 1288 of file GetPot.h.
int operator() (const char * VarName, int Default) const [inline]
Definition at line 1239 of file GetPot.h.
double operator() (const char * VarName, const double & Default) const [inline]
Definition at line 1248 of file GetPot.h.
const char * operator() (const char * VarName, const char * Default) const [inline]
Definition at line 1257 of file GetPot.h.
GetPot & operator= (const GetPot & That) [inline]
Definition at line 438 of file GetPot.h.
Referenced by GetPot().
const char * operator[] (unsigned Idx) const [inline]
Definition at line 885 of file GetPot.h.
bool options_contain (const char * FlagList) const [inline]
Definition at line 1145 of file GetPot.h.
int print () const [inline]
Definition at line 1403 of file GetPot.h.
void reset_cursor () [inline]
Definition at line 874 of file GetPot.h.
Referenced by init_multiple_occurrence().
void reset_nominus_cursor () [inline]
Definition at line 1232 of file GetPot.h.
bool search (unsigned No, const char * P, ...) [inline]
Definition at line 837 of file GetPot.h.
References search().
bool search (const char * option) [inline]
Definition at line 807 of file GetPot.h.
Referenced by follow(), main(), and search().
bool search_failed () const [inline]
Definition at line 115 of file GetPot.h.
void set (const char * VarName, const char * Value, const bool Requested = true) [inline]
Definition at line 1339 of file GetPot.h.
void set (const char * VarName, const double & Value, const bool Requested = true) [inline]
Definition at line 1351 of file GetPot.h.
void set (const char * VarName, const int Value, const bool Requested = true) [inline]
Definition at line 1355 of file GetPot.h.
void set_prefix (const char * Prefix) [inline]
Definition at line 114 of file GetPot.h.
unsigned size () const [inline]
Definition at line 910 of file GetPot.h.
Referenced by main().
STRING_VECTOR unidentified_arguments (unsigned Number, const char * Known, ...) const [inline]
Definition at line 1834 of file GetPot.h.
References unidentified_arguments().
STRING_VECTOR unidentified_arguments (const STRING_VECTOR & Knowns) const [inline]
Definition at line 1858 of file GetPot.h.
STRING_VECTOR unidentified_arguments () const [inline]
Definition at line 1854 of file GetPot.h.
Referenced by unidentified_arguments(), and unidentified_options().
std::string unidentified_flags (const char * Known, int ArgumentNumber = -1) const [inline]
Definition at line 1929 of file GetPot.h.
STRING_VECTOR unidentified_nominuses () const [inline]
Definition at line 2096 of file GetPot.h.
Referenced by unidentified_nominuses().
STRING_VECTOR unidentified_nominuses (const STRING_VECTOR & Knowns) const [inline]
Definition at line 2108 of file GetPot.h.
STRING_VECTOR unidentified_nominuses (unsigned Number, const char * Known, ...) const [inline]
Definition at line 2074 of file GetPot.h.
References unidentified_nominuses().
STRING_VECTOR unidentified_options (const STRING_VECTOR & Knowns) const [inline]
Definition at line 1908 of file GetPot.h.
STRING_VECTOR unidentified_options () const [inline]
Definition at line 1896 of file GetPot.h.
References unidentified_arguments().
Referenced by unidentified_options().
STRING_VECTOR unidentified_options (unsigned Number, const char * Known, ...) const [inline]
Definition at line 1876 of file GetPot.h.
References unidentified_options().
STRING_VECTOR unidentified_sections (const STRING_VECTOR & Knowns) const [inline]
Definition at line 2055 of file GetPot.h.
References victorate.
STRING_VECTOR unidentified_sections (unsigned Number, const char * Known, ...) const [inline]
Definition at line 2027 of file GetPot.h.
References unidentified_sections().
STRING_VECTOR unidentified_sections () const [inline]
Definition at line 2051 of file GetPot.h.
Referenced by unidentified_sections().
STRING_VECTOR unidentified_variables (unsigned Number, const char * Known, ...) const [inline]
Definition at line 1985 of file GetPot.h.
References unidentified_variables().
STRING_VECTOR unidentified_variables () const [inline]
Definition at line 2022 of file GetPot.h.
Referenced by unidentified_variables().
STRING_VECTOR unidentified_variables (const STRING_VECTOR & Knowns) const [inline]
Definition at line 2005 of file GetPot.h.
References victorate.
unsigned vector_variable_size (const char * VarName) const [inline]
Definition at line 1360 of file GetPot.h.
The documentation for this class was generated from the following file:
GetPot.h