CPSTK: WarpTensorMeshFilter< TMesh, TDisplacementField > Class Template Reference
WarpTensorMeshFilter< TMesh, TDisplacementField > Class Template Reference
#include <itkWarpTensorMeshFilter.h>
Public Types
enum ReorientationType { FS, PPD }
typedef WarpTensorMeshFilter Self
typedef TMesh MeshType
typedef MeshToMeshFilter
< MeshType, MeshType > Superclass
typedef MeshType::Pointer MeshPointer
typedef MeshType::PixelType PixelType
typedef SmartPointer< Self > Pointer
typedef SmartPointer< const Self > ConstPointer
typedef PixelType TensorType
typedef PixelType::ValueType ScalarType
typedef MeshType::PointType PointType
typedef
TDisplacementField::RegionType RegionType
typedef TDisplacementField DisplacementFieldType
typedef
DisplacementFieldType::Pointer DisplacementFieldPointer
typedef
DisplacementFieldType::ConstPointer DisplacementFieldConstPointer
typedef
DisplacementFieldType::SpacingType SpacingType
typedef
DisplacementFieldType::IndexType IndexType
typedef Matrix< double,
DisplacementFieldDimension,
VectorDimension > JacobianType
typedef Image< JacobianType,
DisplacementFieldDimension > JacobianImageType
typedef JacobianImageType::Pointer JacobianPointer
typedef WarpJacobianFilter
< TDisplacementField,
JacobianImageType > JacobianFilterType
typedef
VectorLinearInterpolateImageFunction
< DisplacementFieldType,
double > DisplacementInterpolatorType
typedef
DisplacementInterpolatorType::Pointer DisplacementInterpolatorPointer
typedef
DisplacementFieldType::PixelType DisplacementType
typedef ScalarType CoordRepType
typedef
DisplacementFieldType::DirectionType DirectionType
Public Member Functions
virtual const char * GetNameOfClass () const
itkStaticConstMacro (DisplacementFieldDimension, unsigned int, TDisplacementField::ImageDimension)
itkStaticConstMacro (VectorDimension, unsigned int, TDisplacementField::PixelType::Dimension)
virtual JacobianImageType * GetJacobian ()
virtual DisplacementFieldType * GetDisplacementField ()
virtual void SetDisplacementField (DisplacementFieldType *_arg)
virtual DisplacementFieldType * GetInverseDisplacementField ()
virtual void SetInverseDisplacementField (DisplacementFieldType *_arg)
virtual void SetEdgePaddingValue (PixelType _arg)
virtual PixelType GetEdgePaddingValue ()
virtual void SetReorientationStrategy (ReorientationType _arg)
virtual ReorientationType GetReorientationStrategy ()
void GenerateOutputInformation ()
void GenerateInputRequestedRegion ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
WarpTensorMeshFilter ()
~WarpTensorMeshFilter ()
void PrintSelf (std::ostream &os, Indent indent) const
void GenerateData ()
Detailed Description
template<class TMesh, class TDisplacementField>
class itk::WarpTensorMeshFilter< TMesh, TDisplacementField >
Definition at line 37 of file itkWarpTensorMeshFilter.h.
Member Typedef Documentation
typedef SmartPointer<const Self> ConstPointer
Definition at line 50 of file itkWarpTensorMeshFilter.h.
typedef ScalarType CoordRepType
Interpolator typedef support.
Definition at line 93 of file itkWarpTensorMeshFilter.h.
typedef DisplacementFieldType::DirectionType DirectionType
Type for representing the direction of the output image
Definition at line 96 of file itkWarpTensorMeshFilter.h.
typedef DisplacementFieldType::ConstPointer DisplacementFieldConstPointer
Definition at line 67 of file itkWarpTensorMeshFilter.h.
typedef DisplacementFieldType::Pointer DisplacementFieldPointer
Definition at line 66 of file itkWarpTensorMeshFilter.h.
typedef TDisplacementField DisplacementFieldType
Inherit some types from the superclass.
Definition at line 65 of file itkWarpTensorMeshFilter.h.
typedef DisplacementInterpolatorType::Pointer DisplacementInterpolatorPointer
Definition at line 85 of file itkWarpTensorMeshFilter.h.
typedef VectorLinearInterpolateImageFunction<DisplacementFieldType,double> DisplacementInterpolatorType
Interpolator typedef support.
Definition at line 84 of file itkWarpTensorMeshFilter.h.
typedef DisplacementFieldType::PixelType DisplacementType
Displacement field typedef support.
Definition at line 87 of file itkWarpTensorMeshFilter.h.
typedef DisplacementFieldType::IndexType IndexType
Definition at line 69 of file itkWarpTensorMeshFilter.h.
typedef WarpJacobianFilter<TDisplacementField, JacobianImageType> JacobianFilterType
Definition at line 81 of file itkWarpTensorMeshFilter.h.
typedef Image<JacobianType, DisplacementFieldDimension> JacobianImageType
Definition at line 79 of file itkWarpTensorMeshFilter.h.
typedef JacobianImageType::Pointer JacobianPointer
Definition at line 80 of file itkWarpTensorMeshFilter.h.
typedef Matrix<double, DisplacementFieldDimension, VectorDimension> JacobianType
Definition at line 78 of file itkWarpTensorMeshFilter.h.
typedef MeshType::Pointer MeshPointer
Definition at line 46 of file itkWarpTensorMeshFilter.h.
typedef TMesh MeshType
Definition at line 43 of file itkWarpTensorMeshFilter.h.
typedef MeshType::PixelType PixelType
Definition at line 47 of file itkWarpTensorMeshFilter.h.
typedef SmartPointer<Self> Pointer
Definition at line 49 of file itkWarpTensorMeshFilter.h.
typedef MeshType::PointType PointType
Definition at line 57 of file itkWarpTensorMeshFilter.h.
typedef TDisplacementField::RegionType RegionType
Typedef to describe the region type.
Definition at line 62 of file itkWarpTensorMeshFilter.h.
typedef PixelType::ValueType ScalarType
Definition at line 56 of file itkWarpTensorMeshFilter.h.
typedef WarpTensorMeshFilter Self
Standard class typedefs.
Definition at line 42 of file itkWarpTensorMeshFilter.h.
typedef DisplacementFieldType::SpacingType SpacingType
Definition at line 68 of file itkWarpTensorMeshFilter.h.
typedef MeshToMeshFilter< MeshType, MeshType > Superclass
Definition at line 44 of file itkWarpTensorMeshFilter.h.
typedef PixelType TensorType
Definition at line 53 of file itkWarpTensorMeshFilter.h.
Member Enumeration Documentation
enum ReorientationType
Enumerator:
FS
PPD
Definition at line 59 of file itkWarpTensorMeshFilter.h.
Constructor & Destructor Documentation
WarpTensorMeshFilter () [protected]
~WarpTensorMeshFilter () [inline, protected]
Definition at line 121 of file itkWarpTensorMeshFilter.h.
Member Function Documentation
void GenerateData () [protected]
WarpTensorMeshFilter is implemented as a filter. As such, it needs to provide and implementation for GenerateData().
void GenerateInputRequestedRegion ()
void GenerateOutputInformation ()
virtual DisplacementFieldType* GetDisplacementField () [virtual]
virtual PixelType GetEdgePaddingValue () [virtual]
Get the edge padding value
virtual DisplacementFieldType* GetInverseDisplacementField () [virtual]
virtual JacobianImageType* GetJacobian () [virtual]
virtual const char* GetNameOfClass () const [virtual]
virtual ReorientationType GetReorientationStrategy () [virtual]
Get the edge padding value
itkStaticConstMacro (DisplacementFieldDimension , unsigned int, TDisplacementField::ImageDimension)
Determine the image dimension.
itkStaticConstMacro (VectorDimension , unsigned int, TDisplacementField::PixelType::Dimension)
static Pointer New () [static]
Referenced by TensorMeshCostFunction::GetValue(), TensorMeshImageHybridCostFunction3::RecoverOutput(), and TensorMeshImageHybridCostFunction3::TensorMeshImageHybridCostFunction3().
void PrintSelf (std::ostream & os, Indent indent) const [protected]
virtual void SetDisplacementField (DisplacementFieldType * _arg) [virtual]
virtual void SetEdgePaddingValue (PixelType _arg) [virtual]
Set the edge padding value
virtual void SetInverseDisplacementField (DisplacementFieldType * _arg) [virtual]
virtual void SetReorientationStrategy (ReorientationType _arg) [virtual]
Set the type of tensor reorientation
The documentation for this class was generated from the following file:
itkWarpTensorMeshFilter.h