CPSTK: TensorMeshCostFunction Class Reference
TensorMeshCostFunction Class Reference
Tensor processing
This class is a ITK CostFunction returning the difference between tensor fields.
#include <itkTensorMeshCostFunction.h>
Public Types
enum KernelTypeIds { Gaussian = 0, BSpline, KaiserBessel }
typedef TensorMeshCostFunction Self
typedef SingleValuedCostFunction Superclass
typedef SmartPointer< Self > Pointer
typedef SmartPointer< const Self > ConstPointer
typedef double ScalarType
typedef Tensor< ScalarType, 3 > TensorType
typedef
DefaultStaticMeshTraits
< TensorType, 3, 3, ScalarType,
ScalarType, TensorType > MeshTraits
typedef Mesh< TensorType,
3, MeshTraits > TensorMeshType
typedef TensorMeshType::PointType PointType
typedef
TensorMeshType::PointIdentifier PointIdentifier
typedef
GaussianInterpolationTensorMeshFilter
< TensorMeshType > InterpolatorType
typedef Vector< ScalarType, 3 > VectorType
typedef VectorType DisplacementType
typedef Image
< DisplacementType, 3 > DisplacementFieldType
typedef WarpTensorMeshFilter
< TensorMeshType,
DisplacementFieldType > WarperType
typedef
itk::ProlateSpheroidalTransformTensorMeshFilter
< TensorMeshType > CoordinateSwitcherType
typedef
CoordinateSwitcherType::TransformType TransformType
typedef
TensorMeshType::PointsContainer PointContainer
typedef
TensorMeshType::PointDataContainer PixelContainer
typedef GaussianKernelFunction GaussianKernelFunctionType
typedef BSplineKernelFunction< 3 > BSplineKernelFunctionType
typedef KaiserBesselKernelFunction KaiserBesselKernelType
typedef Superclass::MeasureType MeasureType
typedef Superclass::DerivativeType DerivativeType
typedef Superclass::ParametersType ParametersType
typedef
Superclass::ParametersValueType ParametersValueType
Public Member Functions
virtual const char * GetNameOfClass () const
virtual unsigned int GetNumberOfParameters (void) const
virtual MeasureType GetValue (const ParametersType &parameters) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const
void GetBounds (ParametersValueType bds[2][100])
void SetBounds (ParametersValueType bds[2][100])
virtual unsigned int GetUseProlateSpheroidalCoordinates ()
virtual void SetUseProlateSpheroidalCoordinates (unsigned int _arg)
virtual void UseProlateSpheroidalCoordinatesOn ()
virtual void UseProlateSpheroidalCoordinatesOff ()
void SetInputs (TensorMeshType::Pointer data, TensorMeshType::Pointer domain, TensorMeshType::Pointer reference)
void SetDisplacementFields (DisplacementFieldType::Pointer forward, DisplacementFieldType::Pointer backward)
void SetTransform (TransformType::Pointer forward)
bool Copy (const TensorMeshType::Pointer input, TensorMeshType::Pointer output) const
bool WriteMesh (TensorMeshType::Pointer mesh, const char *filename) const
virtual unsigned int GetKernelType () const
virtual void SetKernelType (unsigned int _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
TensorMeshCostFunction ()
virtual ~TensorMeshCostFunction ()
virtual MeasureType EstimateMeanSquaredDistanceBetweenTensorFields (const TensorMeshType::Pointer tensors1, const TensorMeshType::Pointer tensors2) const
virtual MeasureType EstimateMeanAngleDifferenceBetweenTensorFields (const TensorMeshType::Pointer tensors1, const TensorMeshType::Pointer tensors2) const
virtual void UpdatePipeline (void)
Protected Attributes
TensorMeshType::Pointer m_RawData
TensorMeshType::Pointer m_InterpolatedData
TensorMeshType::Pointer m_Reference
TransformType::Pointer m_Transform
DisplacementFieldType::Pointer m_ForwardDisplacementField
DisplacementFieldType::Pointer m_BackwardDisplacementField
bool m_UseProlateSpheroidalCoordinates
unsigned int m_KernelType
ParametersValueType m_WeightLimits [100]
ParametersValueType m_Bounds [2][100]
Detailed Description
This class is a ITK CostFunction returning the difference between tensor fields.
This is a cost function between two tensor fields that are SPARSELY distributed in space. This means the input of the cost function consists on two sets of tensors that are located in (possibly) different positions in space. The tensor sets do NOT have to contain the same amount of tensors.
The mnost important method is SetVariables(). It takes as input the two tensor fields from the following arguments :
Parameters:
pts The first tensor field positions
tns The first tensor field tensors
refpts The second tensor field positions
reftns The second tensor field tensors
The cost function is symmetric and it does not matter if you swap the 2 sets of tensors.
**CAUTION** It is crucial that the amount of points matches the respective amount of tensors.
This cost function works in the Log-space. Thus the input tensors are "logged" prior to processing. In order to be able to compare the two tensor fields, we need them to be located at the same positions. Therefore a tri-linear anisotropic interpolation is performed to the second tensor field onto the first tensor field positions. See InterpolateSparseTensors() for details.
The interpolation uses a anisotropic Gaussian Kernel by default but you can modify the kernel through SetKernel().
The kernel estimate at position is given by:
The main purpose of this class is to return a estimation of the difference between two input tensor fields given a set of input "parameters". The parameters are the sigmas of the anisotropic tri-linear interpolation (Gaussian by default).
If you work in Prolate Coordinate System, please consider using the automatic coordinate switchers : SetChangeCoordinate() and don't forget to switch on SetPiWorkAround().
Todo:
Give the possibility to the user to switch between angle difference and Hosdorff distance between tensor fields.
Author:
Nicolas Toussaint, King's College London, nicolas.toussaint@kcl.ac.uk
Definition at line 86 of file itkTensorMeshCostFunction.h.
Member Typedef Documentation
typedef BSplineKernelFunction<3> BSplineKernelFunctionType
Definition at line 115 of file itkTensorMeshCostFunction.h.
typedef SmartPointer<const Self> ConstPointer
Definition at line 94 of file itkTensorMeshCostFunction.h.
typedef itk::ProlateSpheroidalTransformTensorMeshFilter<TensorMeshType> CoordinateSwitcherType
Definition at line 109 of file itkTensorMeshCostFunction.h.
typedef Superclass::DerivativeType DerivativeType
DerivativeType typedef. It defines a type used to return the cost function derivative.
Definition at line 127 of file itkTensorMeshCostFunction.h.
typedef Image<DisplacementType, 3> DisplacementFieldType
Definition at line 107 of file itkTensorMeshCostFunction.h.
typedef VectorType DisplacementType
Definition at line 106 of file itkTensorMeshCostFunction.h.
typedef GaussianKernelFunction GaussianKernelFunctionType
Definition at line 114 of file itkTensorMeshCostFunction.h.
typedef GaussianInterpolationTensorMeshFilter<TensorMeshType> InterpolatorType
Definition at line 104 of file itkTensorMeshCostFunction.h.
typedef KaiserBesselKernelFunction KaiserBesselKernelType
Definition at line 116 of file itkTensorMeshCostFunction.h.
typedef Superclass::MeasureType MeasureType
MeasureType typedef. It defines a type used to return the cost function value.
Definition at line 121 of file itkTensorMeshCostFunction.h.
typedef DefaultStaticMeshTraits<TensorType, 3, 3, ScalarType, ScalarType, TensorType> MeshTraits
Definition at line 99 of file itkTensorMeshCostFunction.h.
typedef Superclass::ParametersType ParametersType
ParametersType typedef. It defines a position in the optimization search space.
Definition at line 130 of file itkTensorMeshCostFunction.h.
typedef Superclass::ParametersValueType ParametersValueType
ParametersType typedef. It defines a position in the optimization search space.
Definition at line 133 of file itkTensorMeshCostFunction.h.
typedef TensorMeshType::PointDataContainer PixelContainer
Definition at line 112 of file itkTensorMeshCostFunction.h.
typedef TensorMeshType::PointsContainer PointContainer
Definition at line 111 of file itkTensorMeshCostFunction.h.
typedef SmartPointer<Self> Pointer
Definition at line 93 of file itkTensorMeshCostFunction.h.
typedef TensorMeshType::PointIdentifier PointIdentifier
Definition at line 102 of file itkTensorMeshCostFunction.h.
typedef TensorMeshType::PointType PointType
Definition at line 101 of file itkTensorMeshCostFunction.h.
typedef double ScalarType
Definition at line 96 of file itkTensorMeshCostFunction.h.
typedef TensorMeshCostFunction Self
Standard class typedefs.
Definition at line 91 of file itkTensorMeshCostFunction.h.
typedef SingleValuedCostFunction Superclass
Definition at line 92 of file itkTensorMeshCostFunction.h.
typedef Mesh<TensorType, 3, MeshTraits> TensorMeshType
Definition at line 100 of file itkTensorMeshCostFunction.h.
typedef Tensor<ScalarType, 3> TensorType
Definition at line 97 of file itkTensorMeshCostFunction.h.
typedef CoordinateSwitcherType::TransformType TransformType
Definition at line 110 of file itkTensorMeshCostFunction.h.
typedef Vector<ScalarType, 3> VectorType
Definition at line 105 of file itkTensorMeshCostFunction.h.
typedef WarpTensorMeshFilter<TensorMeshType, DisplacementFieldType> WarperType
Definition at line 108 of file itkTensorMeshCostFunction.h.
Member Enumeration Documentation
enum KernelTypeIds
Enumerator:
Gaussian
BSpline
KaiserBessel
Definition at line 193 of file itkTensorMeshCostFunction.h.
Constructor & Destructor Documentation
TensorMeshCostFunction () [protected]
Definition at line 34 of file itkTensorMeshCostFunction.cxx.
References TensorMeshCostFunction::Gaussian.
~TensorMeshCostFunction () [protected, virtual]
Definition at line 59 of file itkTensorMeshCostFunction.cxx.
Member Function Documentation
bool Copy (const TensorMeshType::Pointer input, TensorMeshType::Pointer output) const
Definition at line 296 of file itkTensorMeshCostFunction.cxx.
Referenced by TensorMeshCostFunction::SetInputs().
TensorMeshCostFunction::MeasureType EstimateMeanAngleDifferenceBetweenTensorFields (const TensorMeshType::Pointer tensors1, const TensorMeshType::Pointer tensors2) const [protected, virtual]
This method outputs the mean angle (in degrees) between of 2 distinct tensor fields Tensor arrays must have same size : no check is performed.
Definition at line 249 of file itkTensorMeshCostFunction.cxx.
virtual MeasureType EstimateMeanSquaredDistanceBetweenTensorFields (const TensorMeshType::Pointer tensors1, const TensorMeshType::Pointer tensors2) const [protected, virtual]
This method root mean square distance (in the sense of Frobenius) of 2 distinct tensor fields Tensor arrays must have same size : no check is performed.
void GetBounds (ParametersValueType bds[2][100]) [inline]
Get/Set the bounds of the cost function in the parameter space. If a value is asked with parameters outside those bounds, a maximal cost function value will be returned.
Definition at line 149 of file itkTensorMeshCostFunction.h.
void GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const [virtual]
This method returns the derivative of the cost function corresponding to the specified parameters.
todo !!!
Definition at line 285 of file itkTensorMeshCostFunction.cxx.
virtual unsigned int GetKernelType () const [virtual]
virtual const char* GetNameOfClass () const [virtual]
Run-time type information (and related methods).
virtual unsigned int GetNumberOfParameters (void) const [inline, virtual]
Return the number of parameters required to compute this cost function. This method MUST be overloaded by derived classes.
Definition at line 137 of file itkTensorMeshCostFunction.h.
virtual unsigned int GetUseProlateSpheroidalCoordinates () [virtual]
TensorMeshCostFunction::MeasureType GetValue (const ParametersType & parameters) const [virtual]
This method returns the value of the cost function corresponding to the specified parameters.
Definition at line 77 of file itkTensorMeshCostFunction.cxx.
References TensorMeshCostFunction::BSpline, TensorMeshCostFunction::Gaussian, TensorMeshCostFunction::KaiserBessel, ProlateSpheroidalTransform< TPixelType >::New(), and WarpTensorMeshFilter< TMesh, TDisplacementField >::New().
static Pointer New () [static]
Method for creation through the object factory.
void SetBounds (ParametersValueType bds[2][100]) [inline]
Get/Set the bounds of the cost function in the parameter space. If a value is asked with parameters outside those bounds, a maximal cost function value will be returned.
Definition at line 158 of file itkTensorMeshCostFunction.h.
void SetDisplacementFields (DisplacementFieldType::Pointer forward, DisplacementFieldType::Pointer backward) [inline]
Definition at line 176 of file itkTensorMeshCostFunction.h.
void SetInputs (TensorMeshType::Pointer data, TensorMeshType::Pointer domain, TensorMeshType::Pointer reference)
Set the variables of this cost function.
Parameters:
pts is an array of positions where the measured data are.
Definition at line 64 of file itkTensorMeshCostFunction.cxx.
References TensorMeshCostFunction::Copy(), TensorMeshCostFunction::m_InterpolatedData, TensorMeshCostFunction::m_RawData, TensorMeshCostFunction::m_Reference, and TensorMeshCostFunction::UpdatePipeline().
virtual void SetKernelType (unsigned int _arg) [virtual]
void SetTransform (TransformType::Pointer forward) [inline]
Definition at line 184 of file itkTensorMeshCostFunction.h.
virtual void SetUseProlateSpheroidalCoordinates (unsigned int _arg) [virtual]
virtual void UpdatePipeline (void) [inline, protected, virtual]
Definition at line 218 of file itkTensorMeshCostFunction.h.
Referenced by TensorMeshCostFunction::SetInputs().
virtual void UseProlateSpheroidalCoordinatesOff () [virtual]
virtual void UseProlateSpheroidalCoordinatesOn () [virtual]
bool WriteMesh (TensorMeshType::Pointer mesh, const char * filename) const
Definition at line 356 of file itkTensorMeshCostFunction.cxx.
Member Data Documentation
DisplacementFieldType::Pointer m_BackwardDisplacementField [protected]
Definition at line 229 of file itkTensorMeshCostFunction.h.
ParametersValueType m_Bounds[2][100] [protected]
Definition at line 235 of file itkTensorMeshCostFunction.h.
DisplacementFieldType::Pointer m_ForwardDisplacementField [protected]
Definition at line 228 of file itkTensorMeshCostFunction.h.
TensorMeshType::Pointer m_InterpolatedData [protected]
Definition at line 224 of file itkTensorMeshCostFunction.h.
Referenced by TensorMeshCostFunction::SetInputs().
unsigned int m_KernelType [protected]
Definition at line 232 of file itkTensorMeshCostFunction.h.
TensorMeshType::Pointer m_RawData [protected]
Definition at line 223 of file itkTensorMeshCostFunction.h.
Referenced by TensorMeshCostFunction::SetInputs().
TensorMeshType::Pointer m_Reference [protected]
Definition at line 225 of file itkTensorMeshCostFunction.h.
Referenced by TensorMeshCostFunction::SetInputs().
TransformType::Pointer m_Transform [protected]
Definition at line 227 of file itkTensorMeshCostFunction.h.
bool m_UseProlateSpheroidalCoordinates [protected]
Definition at line 231 of file itkTensorMeshCostFunction.h.
ParametersValueType m_WeightLimits[100] [protected]
Definition at line 234 of file itkTensorMeshCostFunction.h.
The documentation for this class was generated from the following files:
itkTensorMeshCostFunction.h
itkTensorMeshCostFunction.cxx