CPSTK: KaiserBesselKernelFunction Class Reference
KaiserBesselKernelFunction Class Reference
KaiserBessel kernel used for density estimation and nonparameteric regression.
#include <itkKaiserBesselKernelFunction.h>
Public Types
typedef KaiserBesselKernelFunction Self
typedef KernelFunction Superclass
typedef SmartPointer< Self > Pointer
Public Member Functions
virtual const char * GetNameOfClass () const
double Evaluate (const double &u) const
virtual double GetWindowSize ()
virtual double GetBeta ()
void SetWindowSize (double size)
void SetBeta (double beta)
virtual unsigned int GetScaleToUnitIntegral ()
virtual void SetScaleToUnitIntegral (unsigned int _arg)
virtual void ScaleToUnitIntegralOn ()
virtual void ScaleToUnitIntegralOff ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
KaiserBesselKernelFunction ()
~KaiserBesselKernelFunction ()
void PrintSelf (std::ostream &os, Indent indent) const
void ComputeScalingFactor (void)
double I0 (double x) const
Protected Attributes
double m_WindowSize
double m_Beta
double m_ScalingFactor
double m_Resolution
unsigned int m_ScaleToUnitIntegral
Detailed Description
KaiserBessel kernel used for density estimation and nonparameteric regression.
This class encapsulates a KaiserBessel smoothing kernel for density estimation or nonparameteric regression. See documentation for KernelFunction for more details.
The Kaiser-Bessel function is a two-parameter family of functions used for digital signal processing, and is defined by the formula
is the Zero-th order Modified Bessel Function of the first kind.
is a positive real number (usually around 4.0)
is the size of the support (window).
See also:
KernelFunction
Definition at line 58 of file itkKaiserBesselKernelFunction.h.
Member Typedef Documentation
typedef SmartPointer<Self> Pointer
Definition at line 64 of file itkKaiserBesselKernelFunction.h.
typedef KaiserBesselKernelFunction Self
Standard class typedefs.
Definition at line 62 of file itkKaiserBesselKernelFunction.h.
typedef KernelFunction Superclass
Definition at line 63 of file itkKaiserBesselKernelFunction.h.
Constructor & Destructor Documentation
KaiserBesselKernelFunction () [protected]
Definition at line 22 of file itkKaiserBesselKernelFunction.cxx.
References KaiserBesselKernelFunction::ComputeScalingFactor(), KaiserBesselKernelFunction::m_Beta, KaiserBesselKernelFunction::m_Resolution, KaiserBesselKernelFunction::m_ScaleToUnitIntegral, KaiserBesselKernelFunction::m_ScalingFactor, and KaiserBesselKernelFunction::m_WindowSize.
~KaiserBesselKernelFunction () [protected]
Definition at line 33 of file itkKaiserBesselKernelFunction.cxx.
Member Function Documentation
void ComputeScalingFactor (void) [protected]
compute the scaling coefficient.
Definition at line 52 of file itkKaiserBesselKernelFunction.cxx.
References KaiserBesselKernelFunction::I0(), KaiserBesselKernelFunction::m_Beta, KaiserBesselKernelFunction::m_Resolution, KaiserBesselKernelFunction::m_ScalingFactor, and KaiserBesselKernelFunction::m_WindowSize.
Referenced by KaiserBesselKernelFunction::KaiserBesselKernelFunction(), KaiserBesselKernelFunction::SetBeta(), and KaiserBesselKernelFunction::SetWindowSize().
double Evaluate (const double & u) const [inline]
Evaluate the function.
Definition at line 85 of file itkKaiserBesselKernelFunction.h.
virtual double GetBeta () [virtual]
virtual const char* GetNameOfClass () const [virtual]
Run-time type information (and related methods).
virtual unsigned int GetScaleToUnitIntegral () [virtual]
virtual double GetWindowSize () [virtual]
double I0 (double x) const [protected]
Returns the modified Bessel function I0(x) for any real x.
Definition at line 72 of file itkKaiserBesselKernelFunction.cxx.
Referenced by KaiserBesselKernelFunction::ComputeScalingFactor().
static Pointer New () [static]
Method for creation through the object factory.
void PrintSelf (std::ostream & os, Indent indent) const [inline, protected]
Definition at line 114 of file itkKaiserBesselKernelFunction.h.
virtual void ScaleToUnitIntegralOff () [virtual]
virtual void ScaleToUnitIntegralOn () [virtual]
void SetBeta (double beta)
Set the beta parameter and re-compute the scaling coefficient.
Definition at line 45 of file itkKaiserBesselKernelFunction.cxx.
References KaiserBesselKernelFunction::ComputeScalingFactor(), and KaiserBesselKernelFunction::m_Beta.
virtual void SetScaleToUnitIntegral (unsigned int _arg) [virtual]
void SetWindowSize (double size)
Set the window size and re-compute the scaling coefficient.
Definition at line 38 of file itkKaiserBesselKernelFunction.cxx.
References KaiserBesselKernelFunction::ComputeScalingFactor(), and KaiserBesselKernelFunction::m_WindowSize.
Member Data Documentation
double m_Beta [protected]
Definition at line 123 of file itkKaiserBesselKernelFunction.h.
Referenced by KaiserBesselKernelFunction::ComputeScalingFactor(), KaiserBesselKernelFunction::KaiserBesselKernelFunction(), and KaiserBesselKernelFunction::SetBeta().
double m_Resolution [protected]
Definition at line 125 of file itkKaiserBesselKernelFunction.h.
Referenced by KaiserBesselKernelFunction::ComputeScalingFactor(), and KaiserBesselKernelFunction::KaiserBesselKernelFunction().
unsigned int m_ScaleToUnitIntegral [protected]
Definition at line 126 of file itkKaiserBesselKernelFunction.h.
Referenced by KaiserBesselKernelFunction::KaiserBesselKernelFunction().
double m_ScalingFactor [protected]
Definition at line 124 of file itkKaiserBesselKernelFunction.h.
Referenced by KaiserBesselKernelFunction::ComputeScalingFactor(), and KaiserBesselKernelFunction::KaiserBesselKernelFunction().
double m_WindowSize [protected]
Definition at line 122 of file itkKaiserBesselKernelFunction.h.
Referenced by KaiserBesselKernelFunction::ComputeScalingFactor(), KaiserBesselKernelFunction::KaiserBesselKernelFunction(), and KaiserBesselKernelFunction::SetWindowSize().
The documentation for this class was generated from the following files:
itkKaiserBesselKernelFunction.h
itkKaiserBesselKernelFunction.cxx